//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsMessage
    {
        public long ContactUsMessageID { get; set; }
        public string FullName { get; set; }
        public string eMailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string MessageContent { get; set; }
        public bool IsRead { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
