//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int ContactUsID { get; set; }
        public string AboutUs_AR { get; set; }
        public string AboutUs_EN { get; set; }
        public string Address_AR { get; set; }
        public string Address_EN { get; set; }
        public string MobileNumber { get; set; }
        public string FaxNumber { get; set; }
        public string eMailAddress { get; set; }
        public string FaceBookURL { get; set; }
        public string GooglePlusURL { get; set; }
        public string YoutubeURL { get; set; }
        public string TwitterURL { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string FooterStatement_AR { get; set; }
        public string FooterStatement_EN { get; set; }
    }
}
