//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localization
    {
        public int LocalizationID { get; set; }
        public string Code { get; set; }
        public string Page { get; set; }
        public string Lang { get; set; }
        public string Text { get; set; }
    }
}
