//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Requests
    {
        public long ProductRequestID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string FullName { get; set; }
        public string MobileNumber { get; set; }
        public string eMailAddress { get; set; }
        public string Address { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string RequestNotes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDone { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
