//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_ProductAttributeValues = new HashSet<Product_ProductAttributeValues>();
            this.Product_Requests = new HashSet<Product_Requests>();
        }
    
        public long ProductID { get; set; }
        public Nullable<long> ProductTypeID { get; set; }
        public string Name_AR { get; set; }
        public string Name_EN { get; set; }
        public string Description_AR { get; set; }
        public string Description_EN { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public bool IsHighlighted { get; set; }
        public bool IsRecommended { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_ProductAttributeValues> Product_ProductAttributeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Requests> Product_Requests { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
