//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string eMailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string AboutHim { get; set; }
        public string GroupID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool ShowInfoToUsers { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
